# Generated by Django 4.0.4 on 2022-04-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_postitem_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
