# Generated by Django 4.0.4 on 2022-04-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
