# Generated by Django 4.0.4 on 2022-04-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sub', 'subscriber'), ('auth', 'author')], default='sub', max_length=300),
            preserve_default=False,
        ),
    ]
