# Generated by Django 4.0.4 on 2022-04-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_auhor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_subscriber',
        ),
    ]
